language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 8.0
  - nightly

  matrix:
    allow_failures:
      - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
